spring:
  application:
    name: Countries
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3311/country
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 600000

admin:
  username: admin
  password: admin

token:
  ninja: 6AEi0xX6fJROGQP1E6iQTQ==0tT5F9mnoZaGY71h
  secret: fdbf77893be4d92dcd153efc9e63e74fed21237ef7caa85b1eaf3caabbb41d77


